name: sbarbasearch
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - asn1crypto=1.3.0
  - blas=1.0
  - blinker=1.4
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - click=7.0
  - cryptography=2.8
  - elasticsearch=7.0.4
  - flask=1.1.1
  - idna=2.8
  - intel-openmp=2019.5
  - itsdangerous=1.1.0
  - jinja2=2.10.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - markupsafe=1.1.1
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - nltk=3.4.5
  - numpy=1.18.1
  - numpy-base=1.18.1
  - oauthlib=3.1.0
  - openssl=1.1.1d
  - pandas=1.0.0
  - pip=20.0.2
  - pycparser=2.19
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=7.0
  - regex=2019.12.9
  - requests=2.22.0
  - requests-oauthlib=1.3.0
  - setuptools=45.1.0
  - six=1.14.0
  - sqlite=3.30.1
  - tk=8.6.8
  - tweepy=3.8.0
  - urllib3=1.25.8
  - werkzeug=0.16.1
  - wheel=0.34.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - contractions==0.0.24
    - dill==0.3.1.1
    - emoji==0.5.4
    - pandarallel==1.4.5
    - pyahocorasick==1.4.0
    - textsearch==0.0.17
    - unidecode==1.1.1

