name: sbarbasearch
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cython
  - numpy
  - elasticsearch
  - flask
  - nltk
  - pandas
  - pip
  - python==3.7.6
  - regex
  - tweepy
  - pip:
    - contractions
    - emoji
    - pandarallel
    - git+https://github.com/valedica/gensim.git

