name: sbarbasearch
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cython
  - numpy
  - elasticsearch
  - flask
  - nltk
  - pandas
  - pip
  - python
  - regex
  - six
  - tweepy
  - pip:
    - contractions==0.0.24
    - emoji==0.5.4
    - pandarallel==1.4.5
    - git+https://github.com/valedica/gensim.git

